[package]
name = "volar-primitives"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
core = { package = "core", version = "0.0.0", optional = true }