[workspace]
members=["crates/volar-spec", "crates/volar-primitives", "crates/volar-common","crates/volar-dyn", "crates/volar-ir"]
resolver="3"

[workspace.package]
license = "CC0-1.0 AND MIT AND Apache-2.0"
description = "VOLE-in-the-head computations for a cloud world"
repository = "https://github.com/portal-co/volar.git"
[workspace.dependencies]

digest = { version = "0.10.7", default-features = false }
cipher = { version = "0.4.4", default-features = false }
rand =   { version = "0.9.2", default-features = false}
